"""overhaul baseline: account + knowledge domains, no billing

Revision ID: b0d7c5e05dae
Revises: 
Create Date: 2026-08-19 01:08:56.643410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d7c5e05dae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_dictionary',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_job_result_id', sa.String(length=36), nullable=True),
    sa.Column('source_file_name', sa.Text(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('parse_track', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_job_result_id'], ['job_results.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('idx_documents_current_job_result', 'documents', ['current_job_result_id'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('retrieval_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('query_hash', sa.String(length=32), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('chunk_types', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('policy_name', sa.String(length=64), nullable=False),
    sa.Column('agentic_enabled', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('final_doc_ids', sa.JSON(), nullable=True),
    sa.Column('result_provenance', sa.JSON(), nullable=True),
    sa.Column('parent_run_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_step_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_plan', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_retrieval_runs_created', 'retrieval_runs', ['created_at'], unique=False)
    op.create_index('idx_retrieval_runs_query_hash', 'retrieval_runs', ['query_hash'], unique=False)
    op.create_index(op.f('ix_retrieval_runs_parent_run_id'), 'retrieval_runs', ['parent_run_id'], unique=False)
    op.create_table('retrieval_steps',
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_input', sa.JSON(), nullable=True),
    sa.Column('observation', sa.JSON(), nullable=True),
    sa.Column('selected_doc_ids', sa.JSON(), nullable=True),
    sa.Column('selected_paths', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index('idx_retrieval_steps_created', 'retrieval_steps', ['created_at'], unique=False)
    op.create_index('idx_retrieval_steps_run', 'retrieval_steps', ['run_id', 'step_index'], unique=False)
    op.create_index(op.f('ix_retrieval_steps_run_id'), 'retrieval_steps', ['run_id'], unique=False)
    op.create_table('system_limits',
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('api_pattern', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('method', 'api_pattern')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_mask', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('demo_materializations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('demo_source_id', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'namespace', 'demo_source_id', name='uq_demo_materializations_scope_source')
    )
    op.create_index('idx_demo_materializations_document', 'demo_materializations', ['document_id'], unique=False)
    op.create_table('document_attributes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('attr_key', sa.String(length=128), nullable=False),
    sa.Column('attr_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_attributes_key', 'document_attributes', ['attr_key'], unique=False)
    op.create_index(op.f('ix_document_attributes_document_id'), 'document_attributes', ['document_id'], unique=False)
    op.create_table('external_identity_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_subject', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_external_identity_provider_subject')
    )
    op.create_index(op.f('ix_external_identity_links_user_id'), 'external_identity_links', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='Calculated page count (workload estimation)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_job_active_updated_at', 'jobs', ['status', 'updated_at'], unique=False, postgresql_where=sa.text("status IN ('waiting-file', 'pending', 'running', 'converting')"))
    op.create_index('idx_job_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_job_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('idx_job_user_active_states', 'jobs', ['user_id', 'status'], unique=False, postgresql_where=sa.text("status IN ('waiting-file', 'pending', 'running', 'converting')"))
    op.create_index('idx_job_user_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_index('uq_jobs_user_active_document', 'jobs', ['user_id', sa.text("(job_metadata ->> 'document_id')")], unique=True, postgresql_where=sa.text("status IN ('waiting-file', 'pending', 'running', 'converting') AND (job_metadata ->> 'document_id') IS NOT NULL"))
    op.create_table('retrieval_hit_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hit_kind', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retrieval_hit_stats_chunk', 'retrieval_hit_stats', ['chunk_id'], unique=False)
    op.create_index('idx_retrieval_hit_stats_document', 'retrieval_hit_stats', ['document_id'], unique=False)
    op.create_index('uq_retrieval_hit_stats_chunk_key', 'retrieval_hit_stats', ['hit_kind', 'document_id', 'chunk_id'], unique=True, postgresql_where=sa.text('chunk_id IS NOT NULL'))
    op.create_index('uq_retrieval_hit_stats_document_key', 'retrieval_hit_stats', ['hit_kind', 'document_id'], unique=True, postgresql_where=sa.text('chunk_id IS NULL'))
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('webhook_secrets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_secrets_status', 'webhook_secrets', ['status'], unique=False)
    op.create_index('idx_webhook_secrets_user_endpoint', 'webhook_secrets', ['user_id', 'endpoint'], unique=False)
    op.create_index('idx_webhook_secrets_user_id', 'webhook_secrets', ['user_id'], unique=False)
    op.create_table('document_page_plan',
    sa.Column('page_plan_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('shard_plan', sa.JSON(), nullable=True),
    sa.Column('doc_profile', sa.JSON(), nullable=True),
    sa.Column('global_signals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_plan_id')
    )
    op.create_index('idx_document_page_plan_created', 'document_page_plan', ['created_at'], unique=False)
    op.create_index('idx_document_page_plan_job', 'document_page_plan', ['job_id'], unique=False)
    op.create_table('job_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_mode', sa.String(length=20), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('inline_payload', sa.JSON(), nullable=True),
    sa.Column('result_s3_key', sa.String(length=512), nullable=True),
    sa.Column('result_size', sa.Integer(), nullable=True),
    sa.Column('mineru_raw_s3_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_job_results_document_id'), 'job_results', ['document_id'], unique=False)
    op.create_table('job_state_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('transition_reason', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('operator_type', sa.String(length=20), nullable=False),
    sa.Column('transition_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_created_at', 'job_state_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_log_job_created', 'job_state_audit_logs', ['job_id', 'created_at'], unique=False)
    op.create_index('idx_audit_log_job_id', 'job_state_audit_logs', ['job_id'], unique=False)
    op.create_table('job_state_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=False),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('transition_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_state_history_created_at', 'job_state_history', ['created_at'], unique=False)
    op.create_index('idx_job_state_history_job_id', 'job_state_history', ['job_id'], unique=False)
    op.create_table('parse_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('final_status', sa.String(length=32), nullable=False),
    sa.Column('rounds_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_parse_runs_job_kind', 'parse_runs', ['job_id', 'kind'], unique=False)
    op.create_index('idx_parse_runs_started', 'parse_runs', ['started_at'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('qstash_message_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_events_created_at', 'webhook_events', ['created_at'], unique=False)
    op.create_index('idx_webhook_events_job_id', 'webhook_events', ['job_id'], unique=False)
    op.create_index('idx_webhook_events_next_retry', 'webhook_events', ['next_retry_at'], unique=False)
    op.create_index('idx_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_table('document_sections',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('job_result_id', sa.String(length=36), nullable=False),
    sa.Column('parent_section_id', sa.String(length=36), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('section_level', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('section_metadata', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_result_id'], ['job_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_section_id'], ['document_sections.section_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('document_id', 'job_result_id', 'section_path', name='uq_document_sections_revision_path')
    )
    op.create_index('idx_document_sections_doc_revision', 'document_sections', ['document_id', 'job_result_id'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('node_kind', sa.String(length=32), nullable=False),
    sa.Column('owner_document_id', sa.String(length=36), nullable=False),
    sa.Column('job_result_id', sa.String(length=36), nullable=False),
    sa.Column('ref_document_id', sa.String(length=36), nullable=True),
    sa.Column('ref_section_id', sa.String(length=36), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_result_id'], ['job_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index('idx_graph_nodes_owner_revision', 'graph_nodes', ['owner_document_id', 'job_result_id'], unique=False)
    op.create_index('idx_graph_nodes_ref_document', 'graph_nodes', ['ref_document_id'], unique=False)
    op.create_index('idx_graph_nodes_ref_section', 'graph_nodes', ['ref_section_id'], unique=False)
    op.create_table('job_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_result_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_type', sa.String(length=2000), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_result_id'], ['job_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_chunks_chunk_id', 'job_chunks', ['chunk_id'], unique=False)
    op.create_index('idx_job_chunks_result', 'job_chunks', ['job_result_id'], unique=False)
    op.create_table('parse_steps',
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('observation', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['parse_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index('idx_parse_steps_run_round', 'parse_steps', ['run_id', 'round_index'], unique=False)
    op.create_index('idx_parse_steps_tool', 'parse_steps', ['tool_name'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('delivery_provider', sa.String(length=20), server_default='self', nullable=True),
    sa.Column('qstash_message_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['webhook_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_logs_attempt', 'webhook_logs', ['job_id', 'attempt_number'], unique=False)
    op.create_index('idx_webhook_logs_created_at', 'webhook_logs', ['created_at'], unique=False)
    op.create_index('idx_webhook_logs_event_id', 'webhook_logs', ['event_id'], unique=False)
    op.create_index('idx_webhook_logs_job_id', 'webhook_logs', ['job_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('job_result_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_lexical_text', sa.Text(), nullable=True),
    sa.Column('path_lexical_text', sa.Text(), nullable=True),
    sa.Column('content_search_text', sa.Text(), nullable=True),
    sa.Column('path_search_text', sa.Text(), nullable=True),
    sa.Column('term_search_text', sa.Text(), nullable=True),
    sa.Column('content_search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', COALESCE(content_search_text, ''))", persisted=True), nullable=True),
    sa.Column('path_search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', COALESCE(path_search_text, ''))", persisted=True), nullable=True),
    sa.Column('source_chunk_path', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_result_id'], ['job_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.section_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'job_result_id', 'source_chunk_path', name='uq_document_chunks_revision_path')
    )
    op.create_index('idx_chunk_content_search_tsv', 'document_chunks', ['content_search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_chunk_path_search_tsv', 'document_chunks', ['path_search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_document_chunks_chunk_id', 'document_chunks', ['chunk_id'], unique=False)
    op.create_index('idx_document_chunks_doc_revision', 'document_chunks', ['document_id', 'job_result_id'], unique=False)
    op.create_index('idx_document_chunks_section', 'document_chunks', ['section_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('edge_id', sa.String(length=160), nullable=False),
    sa.Column('edge_kind', sa.String(length=32), nullable=False),
    sa.Column('source_node_id', sa.String(length=128), nullable=False),
    sa.Column('target_node_id', sa.String(length=128), nullable=False),
    sa.Column('owner_document_id', sa.String(length=36), nullable=False),
    sa.Column('job_result_id', sa.String(length=36), nullable=False),
    sa.Column('is_directed', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_result_id'], ['job_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index('idx_graph_edges_owner_revision', 'graph_edges', ['owner_document_id', 'job_result_id'], unique=False)
    op.create_index('idx_graph_edges_source', 'graph_edges', ['source_node_id'], unique=False)
    op.create_index('idx_graph_edges_target', 'graph_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###



    # Seed the v2 job-polling system limit (previously migration fbe1c2d3e4f5).
    op.execute(
        """
INSERT INTO system_limits (
    method, api_pattern, priority, rpm, period, description
) VALUES (
    'GET', '/v2/jobs/*', 200, 200, 'minute',
    'Job queries - prevent polling'
)
"""
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_graph_edges_target', table_name='graph_edges')
    op.drop_index('idx_graph_edges_source', table_name='graph_edges')
    op.drop_index('idx_graph_edges_owner_revision', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('idx_document_chunks_section', table_name='document_chunks')
    op.drop_index('idx_document_chunks_doc_revision', table_name='document_chunks')
    op.drop_index('idx_document_chunks_chunk_id', table_name='document_chunks')
    op.drop_index('idx_chunk_path_search_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('idx_chunk_content_search_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_table('document_chunks')
    op.drop_index('idx_webhook_logs_job_id', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_event_id', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_created_at', table_name='webhook_logs')
    op.drop_index('idx_webhook_logs_attempt', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index('idx_parse_steps_tool', table_name='parse_steps')
    op.drop_index('idx_parse_steps_run_round', table_name='parse_steps')
    op.drop_table('parse_steps')
    op.drop_index('idx_job_chunks_result', table_name='job_chunks')
    op.drop_index('idx_job_chunks_chunk_id', table_name='job_chunks')
    op.drop_table('job_chunks')
    op.drop_index('idx_graph_nodes_ref_section', table_name='graph_nodes')
    op.drop_index('idx_graph_nodes_ref_document', table_name='graph_nodes')
    op.drop_index('idx_graph_nodes_owner_revision', table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index('idx_document_sections_doc_revision', table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index('idx_webhook_events_status', table_name='webhook_events')
    op.drop_index('idx_webhook_events_next_retry', table_name='webhook_events')
    op.drop_index('idx_webhook_events_job_id', table_name='webhook_events')
    op.drop_index('idx_webhook_events_created_at', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('idx_parse_runs_started', table_name='parse_runs')
    op.drop_index('idx_parse_runs_job_kind', table_name='parse_runs')
    op.drop_table('parse_runs')
    op.drop_index('idx_job_state_history_job_id', table_name='job_state_history')
    op.drop_index('idx_job_state_history_created_at', table_name='job_state_history')
    op.drop_table('job_state_history')
    op.drop_index('idx_audit_log_job_id', table_name='job_state_audit_logs')
    op.drop_index('idx_audit_log_job_created', table_name='job_state_audit_logs')
    op.drop_index('idx_audit_log_created_at', table_name='job_state_audit_logs')
    op.drop_table('job_state_audit_logs')
    op.drop_index(op.f('ix_job_results_document_id'), table_name='job_results')
    op.drop_table('job_results')
    op.drop_index('idx_document_page_plan_job', table_name='document_page_plan')
    op.drop_index('idx_document_page_plan_created', table_name='document_page_plan')
    op.drop_table('document_page_plan')
    op.drop_index('idx_webhook_secrets_user_id', table_name='webhook_secrets')
    op.drop_index('idx_webhook_secrets_user_endpoint', table_name='webhook_secrets')
    op.drop_index('idx_webhook_secrets_status', table_name='webhook_secrets')
    op.drop_table('webhook_secrets')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_retrieval_hit_stats_document_key', table_name='retrieval_hit_stats', postgresql_where=sa.text('chunk_id IS NULL'))
    op.drop_index('uq_retrieval_hit_stats_chunk_key', table_name='retrieval_hit_stats', postgresql_where=sa.text('chunk_id IS NOT NULL'))
    op.drop_index('idx_retrieval_hit_stats_document', table_name='retrieval_hit_stats')
    op.drop_index('idx_retrieval_hit_stats_chunk', table_name='retrieval_hit_stats')
    op.drop_table('retrieval_hit_stats')
    op.drop_index('uq_jobs_user_active_document', table_name='jobs', postgresql_where=sa.text("status IN ('waiting-file', 'pending', 'running', 'converting') AND (job_metadata ->> 'document_id') IS NOT NULL"))
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index('idx_job_user_status', table_name='jobs')
    op.drop_index('idx_job_user_active_states', table_name='jobs', postgresql_where=sa.text("status IN ('waiting-file', 'pending', 'running', 'converting')"))
    op.drop_index('idx_job_type', table_name='jobs')
    op.drop_index('idx_job_status', table_name='jobs')
    op.drop_index('idx_job_created_at', table_name='jobs')
    op.drop_index('idx_job_active_updated_at', table_name='jobs', postgresql_where=sa.text("status IN ('waiting-file', 'pending', 'running', 'converting')"))
    op.drop_table('jobs')
    op.drop_index(op.f('ix_external_identity_links_user_id'), table_name='external_identity_links')
    op.drop_table('external_identity_links')
    op.drop_index(op.f('ix_document_attributes_document_id'), table_name='document_attributes')
    op.drop_index('idx_document_attributes_key', table_name='document_attributes')
    op.drop_table('document_attributes')
    op.drop_index('idx_demo_materializations_document', table_name='demo_materializations')
    op.drop_table('demo_materializations')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('system_limits')
    op.drop_index(op.f('ix_retrieval_steps_run_id'), table_name='retrieval_steps')
    op.drop_index('idx_retrieval_steps_run', table_name='retrieval_steps')
    op.drop_index('idx_retrieval_steps_created', table_name='retrieval_steps')
    op.drop_table('retrieval_steps')
    op.drop_index(op.f('ix_retrieval_runs_parent_run_id'), table_name='retrieval_runs')
    op.drop_index('idx_retrieval_runs_query_hash', table_name='retrieval_runs')
    op.drop_index('idx_retrieval_runs_created', table_name='retrieval_runs')
    op.drop_table('retrieval_runs')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_current_job_result', table_name='documents')
    op.drop_table('documents')
    op.drop_table('attribute_dictionary')
    # ### end Alembic commands ###
